In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
# ==========================================================
# Load the scraped dataset
# ==========================================================

df = pd.read_csv("../data/books.csv")

print("Dataset Loaded Successfully")

df.head()

Dataset Loaded Successfully

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
0,It's Only the Himalayas,Travel,£45.17,Two,In stock (19 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,0,https://books.toscrape.com/catalogue/its-only-...
1,Libertarianism for Beginners,Politics,£51.33,Two,In stock (19 available)\n \n\n \n \n ...,Libertarianism isn't about winning elections; ...,a18a4f574854aced,0,https://books.toscrape.com/catalogue/libertari...
2,Mesaerion: The Best Science Fiction Stories 18...,Science Fiction,£37.59,One,In stock (19 available)\n \n\n \n \n ...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,0,https://books.toscrape.com/catalogue/mesaerion...
3,Olio,Poetry,£23.88,One,In stock (19 available)\n \n\n \n \n ...,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,0,https://books.toscrape.com/catalogue/olio_984/...
4,Our Band Could Be Your Life: Scenes from the A...,Music,£57.25,Three,In stock (19 available)\n \n\n \n \n ...,This is the never-before-told story of the mus...,deda3e61b9514b83,0,https://books.toscrape.com/catalogue/our-band-...

In [3]:
# ==========================================================
# Display dataset information
# ==========================================================

print("Shape of Dataset :", df.shape)

print("\nColumn Names\n")
print(df.columns)

print("\nDataset Information\n")
df.info()

Shape of Dataset : (100, 9)

Column Names

Index(['Title', 'Category', 'Price', 'Rating', 'Availability',
       'Product Description', 'UPC', 'Number of Reviews', 'Product URL'],
      dtype='object')

Dataset Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                100 non-null    object
 1   Category             100 non-null    object
 2   Price                100 non-null    object
 3   Rating               100 non-null    object
 4   Availability         100 non-null    object
 5   Product Description  100 non-null    object
 6   UPC                  100 non-null    object
 7   Number of Reviews    100 non-null    int64
 8   Product URL          100 non-null    object
dtypes: int64(1), object(8)
memory usage: 7.2+ KB

In [4]:
# ==========================================================
# Statistical Summary
# ==========================================================

df.describe(include="all")

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
count,100,100,100,100,100,100,100,100.0,100
unique,100,29,99,5,10,100,100,NaN,100
top,It's Only the Himalayas,Sequential Art,£44.18,One,In stock (16 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,NaN,https://books.toscrape.com/catalogue/its-only-...
freq,1,14,2,22,56,1,1,NaN,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [5]:
# ==========================================================
# Check Missing Values
# ==========================================================

missing_values = df.isnull().sum()

print(missing_values)

Title                  0
Category               0
Price                  0
Rating                 0
Availability           0
Product Description    0
UPC                    0
Number of Reviews      0
Product URL            0
dtype: int64

In [6]:
# ==========================================================
# Percentage Missing Values
# ==========================================================

missing_percentage = (df.isnull().sum()/len(df))*100

missing_percentage

Title                  0.0
Category               0.0
Price                  0.0
Rating                 0.0
Availability           0.0
Product Description    0.0
UPC                    0.0
Number of Reviews      0.0
Product URL            0.0
dtype: float64

In [7]:
# ==========================================================
# Check Duplicate Records
# ==========================================================

duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [8]:
# ==========================================================
# Remove Duplicate Rows
# ==========================================================

df.drop_duplicates(inplace=True)

print("New Shape :", df.shape)

New Shape : (100, 9)

In [9]:
# ==========================================================
# Check Duplicate UPC
# ==========================================================

duplicate_upc = df["UPC"].duplicated().sum()

print("Duplicate UPC :", duplicate_upc)

Duplicate UPC : 0

In [10]:
# ==========================================================
# Remove Pound Symbol
# ==========================================================

df["Price"] = df["Price"].str.replace("£","",regex=False)

df["Price"] = df["Price"].astype(float)

df.head()

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
0,It's Only the Himalayas,Travel,45.17,Two,In stock (19 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,0,https://books.toscrape.com/catalogue/its-only-...
1,Libertarianism for Beginners,Politics,51.33,Two,In stock (19 available)\n \n\n \n \n ...,Libertarianism isn't about winning elections; ...,a18a4f574854aced,0,https://books.toscrape.com/catalogue/libertari...
2,Mesaerion: The Best Science Fiction Stories 18...,Science Fiction,37.59,One,In stock (19 available)\n \n\n \n \n ...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,0,https://books.toscrape.com/catalogue/mesaerion...
3,Olio,Poetry,23.88,One,In stock (19 available)\n \n\n \n \n ...,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,0,https://books.toscrape.com/catalogue/olio_984/...
4,Our Band Could Be Your Life: Scenes from the A...,Music,57.25,Three,In stock (19 available)\n \n\n \n \n ...,This is the never-before-told story of the mus...,deda3e61b9514b83,0,https://books.toscrape.com/catalogue/our-band-...

In [11]:
# ==========================================================
# Convert Rating into Numeric Values
# ==========================================================

rating_map = {

    "One":1,

    "Two":2,

    "Three":3,

    "Four":4,

    "Five":5

}

df["Rating"] = df["Rating"].map(rating_map)

df.head()

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
0,It's Only the Himalayas,Travel,45.17,2,In stock (19 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,0,https://books.toscrape.com/catalogue/its-only-...
1,Libertarianism for Beginners,Politics,51.33,2,In stock (19 available)\n \n\n \n \n ...,Libertarianism isn't about winning elections; ...,a18a4f574854aced,0,https://books.toscrape.com/catalogue/libertari...
2,Mesaerion: The Best Science Fiction Stories 18...,Science Fiction,37.59,1,In stock (19 available)\n \n\n \n \n ...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,0,https://books.toscrape.com/catalogue/mesaerion...
3,Olio,Poetry,23.88,1,In stock (19 available)\n \n\n \n \n ...,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,0,https://books.toscrape.com/catalogue/olio_984/...
4,Our Band Could Be Your Life: Scenes from the A...,Music,57.25,3,In stock (19 available)\n \n\n \n \n ...,This is the never-before-told story of the mus...,deda3e61b9514b83,0,https://books.toscrape.com/catalogue/our-band-...

In [12]:
# ==========================================================
# Clean Availability Column
# ==========================================================

df["Availability"] = df["Availability"].str.strip()

df.head()

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
0,It's Only the Himalayas,Travel,45.17,2,In stock (19 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,0,https://books.toscrape.com/catalogue/its-only-...
1,Libertarianism for Beginners,Politics,51.33,2,In stock (19 available)\n \n\n \n \n ...,Libertarianism isn't about winning elections; ...,a18a4f574854aced,0,https://books.toscrape.com/catalogue/libertari...
2,Mesaerion: The Best Science Fiction Stories 18...,Science Fiction,37.59,1,In stock (19 available)\n \n\n \n \n ...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,0,https://books.toscrape.com/catalogue/mesaerion...
3,Olio,Poetry,23.88,1,In stock (19 available)\n \n\n \n \n ...,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,0,https://books.toscrape.com/catalogue/olio_984/...
4,Our Band Could Be Your Life: Scenes from the A...,Music,57.25,3,In stock (19 available)\n \n\n \n \n ...,This is the never-before-told story of the mus...,deda3e61b9514b83,0,https://books.toscrape.com/catalogue/our-band-...

In [13]:
# ==========================================================
# Convert Reviews into Integer
# ==========================================================

df["Number of Reviews"] = df["Number of Reviews"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                100 non-null    object
 1   Category             100 non-null    object
 2   Price                100 non-null    float64
 3   Rating               100 non-null    int64
 4   Availability         100 non-null    object
 5   Product Description  100 non-null    object
 6   UPC                  100 non-null    object
 7   Number of Reviews    100 non-null    int64
 8   Product URL          100 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 7.2+ KB

In [14]:
# ==========================================================
# Fill Missing Description
# ==========================================================

df["Product Description"] = df["Product Description"].fillna("No Description Available")

In [15]:
# ==========================================================
# Verify Data Types
# ==========================================================

df.dtypes

Title                   object
Category                object
Price                  float64
Rating                   int64
Availability            object
Product Description     object
UPC                     object
Number of Reviews        int64
Product URL             object
dtype: object

In [16]:
# ==========================================================
# Final Missing Value Check
# ==========================================================

df.isnull().sum()

Title                  0
Category               0
Price                  0
Rating                 0
Availability           0
Product Description    0
UPC                    0
Number of Reviews      0
Product URL            0
dtype: int64

In [17]:
# ==========================================================
# Final Dataset Information
# ==========================================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Title                100 non-null    object
 1   Category             100 non-null    object
 2   Price                100 non-null    float64
 3   Rating               100 non-null    int64
 4   Availability         100 non-null    object
 5   Product Description  100 non-null    object
 6   UPC                  100 non-null    object
 7   Number of Reviews    100 non-null    int64
 8   Product URL          100 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 7.2+ KB

In [18]:
# ==========================================================
# Save Cleaned Dataset
# ==========================================================

df.to_csv("../data/books_cleaned.csv",index=False)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [19]:
# ==========================================================
# Display Clean Dataset
# ==========================================================

df.head(10)

,Title,Category,Price,Rating,Availability,Product Description,UPC,Number of Reviews,Product URL
0,It's Only the Himalayas,Travel,45.17,2,In stock (19 available)\n \n\n \n \n ...,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,0,https://books.toscrape.com/catalogue/its-only-...
1,Libertarianism for Beginners,Politics,51.33,2,In stock (19 available)\n \n\n \n \n ...,Libertarianism isn't about winning elections; ...,a18a4f574854aced,0,https://books.toscrape.com/catalogue/libertari...
2,Mesaerion: The Best Science Fiction Stories 18...,Science Fiction,37.59,1,In stock (19 available)\n \n\n \n \n ...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,0,https://books.toscrape.com/catalogue/mesaerion...
3,Olio,Poetry,23.88,1,In stock (19 available)\n \n\n \n \n ...,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,0,https://books.toscrape.com/catalogue/olio_984/...
4,Our Band Could Be Your Life: Scenes from the A...,Music,57.25,3,In stock (19 available)\n \n\n \n \n ...,This is the never-before-told story of the mus...,deda3e61b9514b83,0,https://books.toscrape.com/catalogue/our-band-...
5,Rip it Up and Start Again,Music,35.02,5,In stock (19 available)\n \n\n \n \n ...,"Punk's raw power rejuvenated rock, but by the ...",a34ba96d4081e6a4,0,https://books.toscrape.com/catalogue/rip-it-up...
6,Scott Pilgrim's Precious Little Life (Scott Pi...,Sequential Art,52.29,5,In stock (19 available)\n \n\n \n \n ...,Scott Pilgrim's life is totally sweet. He's 23...,3b1c02bac2a429e6,0,https://books.toscrape.com/catalogue/scott-pil...
7,Set Me Free,Young Adult,17.46,5,In stock (19 available)\n \n\n \n \n ...,Aaron Ledbetter’s future had been planned out ...,ce6396b0f23f6ecc,0,https://books.toscrape.com/catalogue/set-me-fr...
8,Shakespeare's Sonnets,Poetry,20.66,4,In stock (19 available)\n \n\n \n \n ...,This book is an important and complete collect...,30a7f60cd76ca58c,0,https://books.toscrape.com/catalogue/shakespea...
9,"Starving Hearts (Triangular Trade Trilogy, #1)",Default,13.99,2,In stock (19 available)\n \n\n \n \n ...,"Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,0,https://books.toscrape.com/catalogue/starving-...

In [20]:
# ==========================================================
# Extract Available Stock Count from Availability Column
# ==========================================================

import re

def extract_stock(text):
    """
    Extract the number of books available in stock.
    Example:
        'In stock (22 available)' -> 22
        'In stock' -> 0
    """

    if pd.isna(text):
        return 0

    match = re.search(r'(\d+)', text)

    if match:
        return int(match.group(1))
    else:
        return 0


df["Available Stock"] = df["Availability"].apply(extract_stock)

df[["Availability", "Available Stock"]].head()

                                        Availability  Available Stock
0  In stock (19 available)\n    \n\n    \n    \n ...               19
1  In stock (19 available)\n    \n\n    \n    \n ...               19
2  In stock (19 available)\n    \n\n    \n    \n ...               19
3  In stock (19 available)\n    \n\n    \n    \n ...               19
4  In stock (19 available)\n    \n\n    \n    \n ...               19

In [21]:
# ==========================================================
# Feature 1 : Description Word Count
# ==========================================================

df["description_word_count"] = (
    df["Product Description"]
    .fillna("")
    .apply(lambda x: len(str(x).split()))
)

df[["Product Description", "description_word_count"]].head()

                                 Product Description  description_word_count
0  “Wherever you go, whatever you do, just . . . ...                     230
1  Libertarianism isn't about winning elections; ...                     195
2  Andrew Barger, award-winning author and engine...                     283
3  Part fact, part fiction, Tyehimba Jess's much ...                     249
4  This is the never-before-told story of the mus...                     163

In [22]:
# ==========================================================
# Feature 2 : Price Band
# ==========================================================

df["price_band"] = pd.cut(
    df["Price"],
    bins=[0, 20, 35, 50, float("inf")],
    labels=["Budget", "Economy", "Premium", "Luxury"]
)

df[["Price", "price_band"]].head()

   Price price_band
0  45.17    Premium
1  51.33     Luxury
2  37.59    Premium
3  23.88    Economy
4  57.25     Luxury

In [23]:
# ==========================================================
# Feature 3 : Affordability Score
# ==========================================================

max_price = df["Price"].max()

df["affordability_score"] = (
    (max_price - df["Price"]) / max_price
).round(3)

df[["Price", "affordability_score"]].head()

   Price  affordability_score
0  45.17                0.223
1  51.33                0.117
2  37.59                0.353
3  23.88                0.589
4  57.25                0.015

In [24]:
# ==========================================================
# Feature 4 : Value Score
# ==========================================================

df["value_score"] = (
    df["Rating"] * df["affordability_score"]
).round(2)

df[["Rating", "Price", "value_score"]].head()

   Rating  Price  value_score
0       2  45.17         0.45
1       2  51.33         0.23
2       1  37.59         0.35
3       1  23.88         0.59
4       3  57.25         0.04

In [25]:
# ==========================================================
# Feature 5 : Recommended
# ==========================================================

df["recommended"] = np.where(
    (df["Rating"] >= 4) &
    (df["Price"] <= 35),
    "Yes",
    "No"
)

df[["Rating", "Price", "recommended"]].head()

   Rating  Price recommended
0       2  45.17          No
1       2  51.33          No
2       1  37.59          No
3       1  23.88          No
4       3  57.25          No

In [26]:
# ==========================================================
# Display Newly Created Features
# ==========================================================

new_features = [

    "Available Stock",

    "description_word_count",

    "price_band",

    "affordability_score",

    "value_score",

    "recommended"

]

df[new_features].head(10)

,Available Stock,description_word_count,price_band,affordability_score,value_score,recommended
0,19,230,Premium,0.223,0.45,No
1,19,195,Luxury,0.117,0.23,No
2,19,283,Premium,0.353,0.35,No
3,19,249,Economy,0.589,0.59,No
4,19,163,Luxury,0.015,0.04,No
5,19,148,Premium,0.397,1.98,No
6,19,148,Luxury,0.100,0.50,No
7,19,132,Budget,0.700,3.50,Yes
8,19,143,Economy,0.644,2.58,Yes
9,19,196,Budget,0.759,1.52,No

In [27]:
# ==========================================================
# Final Dataset Summary
# ==========================================================

print("Final Shape :", df.shape)

print("\nColumns\n")

print(df.columns)

print("\nData Types\n")

print(df.dtypes)

Final Shape : (100, 15)

Columns

Index(['Title', 'Category', 'Price', 'Rating', 'Availability',
       'Product Description', 'UPC', 'Number of Reviews', 'Product URL',
       'Available Stock', 'description_word_count', 'price_band',
       'affordability_score', 'value_score', 'recommended'],
      dtype='object')

Data Types

Title                       object
Category                    object
Price                      float64
Rating                       int64
Availability                object
Product Description         object
UPC                         object
Number of Reviews            int64
Product URL                 object
Available Stock              int64
description_word_count       int64
price_band                category
affordability_score        float64
value_score                float64
recommended                 object
dtype: object

In [ ]:
# ==========================================================
# Save Final Cleaned Dataset
# ==========================================================

output_path = "../data/books_cleaned.csv"

df.to_csv(output_path, index=False)

print("===========================================")
print("Dataset Saved Successfully")
print("Location :", output_path)
print("===========================================")

===========================================
Dataset Saved Successfully
Location : ../data/books_cleaned.csv
===========================================